### ISSUE TITLE
What will be different ?

### ISSUE THREAD

**Issue by moeenio** [ScratcherNetwork/scratchernetwork.github.io#1]
What will be different from ScratchNetwork ?

**Comment by MasterOfTheTiger** [comment]
It will be fully free/libre and open source. I it will also be decentralized so that you can verify it.

**Comment by moeenio** [comment]
What do you mean by "decentralised" ?

**Comment by MasterOfTheTiger** [comment]
No one computer will run it. Multiple computers will work together to run it, all owned by different people. That is my simple explanation.

**Comment by moeenio** [comment]
And how you can contribute to run it ?

**Comment by moeenio** [comment]
Multiple computers will run a separate backend and client, and clients can connect to any backends ?

**Comment by MasterOfTheTiger** [comment]
I hope to make it decentralized, but it is looking like it is going to take a lot more work than I previously thought, the first version will be a direct fork of ScratchNetwork, and will be very similar, but without the contriversial practices. Maybe Myed can be a big contributor as well. ScratchNetwork is open source now, so I have less objections to it. But it was banned from Scratch because of its moderation practices. ScratcherNetwork will have to have adult moderators as well.

**Comment by moeenio** [comment]
I think you could avoid Scratch by making a non-Scratch-based account system first.
Do you know OpenID ?

**Comment by MasterOfTheTiger** [comment]
No I do not. Also, you are not allowed to advertise websites on Scratch that ask for email. I think that using Scratch accounts are the best way to go if we want to advertise it on Scratch. 

I have never actually understood OpenID fully. Can you explain it a bit?

**Comment by moeenio** [comment]
It looks like it is a login system, that lets you login with a website URL, but I don't really understand it too.

**Comment by moeenio** [comment]
Hi.
